### ISSUE TITLE
Joining a pool

### ISSUE THREAD

**Issue by bhkeys** [bigreddmachine/MoneroPy#3]
I would like to make a python application that embeds a monero miner and joins a pool.
Is it possible to use this API to join a monero pool and start mining?

**Comment by bigreddmachine** [comment]
Well... two things...

1. This isn't an API. it's a tool set that does stuff, rather than connect to things.
2. This doesn't have anything mining related in it, so I don't see how it would be any help.

That being said, you certainly could build a Python App that has a monero miner embedded in, perhaps this miner: https://github.com/fireice-uk/xmr-stak-cpu

But I really don't see how MoneroPy would be of any help there...
